/// <reference types="react" />
import * as PropTypes from 'prop-types';
import * as React from 'react';
import Stateless from 'wasabi-ui/lib/Stateless';
/**
 * Provides abstraction from HTML Elements.
 */
declare abstract class AbstractDom<P extends HTMLElementProps> extends Stateless<P> {
    static propTypes: {
        className: PropTypes.Requireable<any>;
        style: PropTypes.Requireable<any>;
    };
    static defaultProps: {
        className: string;
        style: {};
    };
    static create(): void;
    classNames(clazzNames: string[]): string;
}
export default AbstractDom;
/**
 * Refers properties of HTML Elements.
 */
export declare type HTMLAllAttributes = React.AllHTMLAttributes<HTMLElement>;
export declare type HTMLElementProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLAProps = React.AnchorHTMLAttributes<HTMLAnchorElement>;
export declare type HTMLAbbrProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLAddressProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLAreaProps = React.AreaHTMLAttributes<HTMLAreaElement>;
export declare type HTMLArticleProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLAsideProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLAudioProps = React.AudioHTMLAttributes<HTMLAudioElement>;
export declare type HTMLBProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLBaseProps = React.BaseHTMLAttributes<HTMLBaseElement>;
export declare type HTMLBdiProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLBdoProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLBigProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLBlockquoteProps = React.BlockquoteHTMLAttributes<HTMLElement>;
export declare type HTMLBodyProps = React.HTMLAttributes<HTMLBodyElement>;
export declare type HTMLBrProps = React.HTMLAttributes<HTMLBRElement>;
export declare type HTMLButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement>;
export declare type HTMLCanvasProps = React.CanvasHTMLAttributes<HTMLCanvasElement>;
export declare type HTMLCaptionProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLCiteProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLCodeProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLColProps = React.ColHTMLAttributes<HTMLTableColElement>;
export declare type HTMLColgroupProps = React.ColgroupHTMLAttributes<HTMLTableColElement>;
export declare type HTMLDataProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLDatalistProps = React.HTMLAttributes<HTMLDataListElement>;
export declare type HTMLDdProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLDelProps = React.DelHTMLAttributes<HTMLElement>;
export declare type HTMLDetailsProps = React.DetailsHTMLAttributes<HTMLElement>;
export declare type HTMLDfnProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLDialogProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLDivProps = React.HTMLAttributes<HTMLDivElement>;
export declare type HTMLDlProps = React.HTMLAttributes<HTMLDListElement>;
export declare type HTMLDtProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLEmProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLEmbedProps = React.EmbedHTMLAttributes<HTMLEmbedElement>;
export declare type HTMLFieldsetProps = React.FieldsetHTMLAttributes<HTMLFieldSetElement>;
export declare type HTMLFigcaptionProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLFigureProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLFooterProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLFormProps = React.FormHTMLAttributes<HTMLFormElement>;
export declare type HTMLH1Props = React.HTMLAttributes<HTMLHeadingElement>;
export declare type HTMLH2Props = React.HTMLAttributes<HTMLHeadingElement>;
export declare type HTMLH3Props = React.HTMLAttributes<HTMLHeadingElement>;
export declare type HTMLH4Props = React.HTMLAttributes<HTMLHeadingElement>;
export declare type HTMLH5Props = React.HTMLAttributes<HTMLHeadingElement>;
export declare type HTMLH6Props = React.HTMLAttributes<HTMLHeadingElement>;
export declare type HTMLHeadProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLHeaderProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLHgroupProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLHrProps = React.HTMLAttributes<HTMLHRElement>;
export declare type HTMLHtmlProps = React.HtmlHTMLAttributes<HTMLHtmlElement>;
export declare type HTMLIProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLIframeProps = React.IframeHTMLAttributes<HTMLIFrameElement>;
export declare type HTMLImgProps = React.ImgHTMLAttributes<HTMLImageElement>;
export declare type HTMLInputProps = React.InputHTMLAttributes<HTMLInputElement>;
export declare type HTMLInsProps = React.InsHTMLAttributes<HTMLModElement>;
export declare type HTMLKbdProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLKeygenProps = React.KeygenHTMLAttributes<HTMLElement>;
export declare type HTMLLabelProps = React.LabelHTMLAttributes<HTMLLabelElement>;
export declare type HTMLLegendProps = React.HTMLAttributes<HTMLLegendElement>;
export declare type HTMLLiProps = React.LiHTMLAttributes<HTMLLIElement>;
export declare type HTMLLinkProps = React.LinkHTMLAttributes<HTMLLinkElement>;
export declare type HTMLMainProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLMapProps = React.MapHTMLAttributes<HTMLMapElement>;
export declare type HTMLMarkProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLMenuProps = React.MenuHTMLAttributes<HTMLElement>;
export declare type HTMLMenuitemProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLMetaProps = React.MetaHTMLAttributes<HTMLMetaElement>;
export declare type HTMLMeterProps = React.MeterHTMLAttributes<HTMLElement>;
export declare type HTMLNavProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLNoscriptProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLObjectProps = React.ObjectHTMLAttributes<HTMLObjectElement>;
export declare type HTMLOlProps = React.OlHTMLAttributes<HTMLOListElement>;
export declare type HTMLOptgroupProps = React.OptgroupHTMLAttributes<HTMLOptGroupElement>;
export declare type HTMLOptionProps = React.OptionHTMLAttributes<HTMLOptionElement>;
export declare type HTMLOutputProps = React.OutputHTMLAttributes<HTMLElement>;
export declare type HTMLPProps = React.HTMLAttributes<HTMLParagraphElement>;
export declare type HTMLParamProps = React.ParamHTMLAttributes<HTMLParamElement>;
export declare type HTMLPictureProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLPreProps = React.HTMLAttributes<HTMLPreElement>;
export declare type HTMLProgressProps = React.ProgressHTMLAttributes<HTMLProgressElement>;
export declare type HTMLQProps = React.QuoteHTMLAttributes<HTMLQuoteElement>;
export declare type HTMLRpProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLRtProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLRubyProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLSProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLSampProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLScriptProps = React.ScriptHTMLAttributes<HTMLScriptElement>;
export declare type HTMLSectionProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLSelectProps = React.SelectHTMLAttributes<HTMLSelectElement>;
export declare type HTMLSmallProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLSourceProps = React.SourceHTMLAttributes<HTMLSourceElement>;
export declare type HTMLSpanProps = React.HTMLAttributes<HTMLSpanElement>;
export declare type HTMLStrongProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLStyleProps = React.StyleHTMLAttributes<HTMLStyleElement>;
export declare type HTMLSubProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLSummaryProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLSupProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLTableProps = React.TableHTMLAttributes<HTMLTableElement>;
export declare type HTMLTbodyProps = React.HTMLAttributes<HTMLTableSectionElement>;
export declare type HTMLTdProps = React.TdHTMLAttributes<HTMLTableDataCellElement>;
export declare type HTMLTextareaProps = React.TextareaHTMLAttributes<HTMLTextAreaElement>;
export declare type HTMLTfootProps = React.HTMLAttributes<HTMLTableSectionElement>;
export declare type HTMLThProps = React.ThHTMLAttributes<HTMLTableHeaderCellElement>;
export declare type HTMLTheadProps = React.HTMLAttributes<HTMLTableSectionElement>;
export declare type HTMLTimeProps = React.TimeHTMLAttributes<HTMLElement>;
export declare type HTMLTitleProps = React.HTMLAttributes<HTMLTitleElement>;
export declare type HTMLTrProps = React.HTMLAttributes<HTMLTableRowElement>;
export declare type HTMLTrackProps = React.TrackHTMLAttributes<HTMLTrackElement>;
export declare type HTMLUProps = React.HTMLAttributes<HTMLElement>;
export declare type HTMLUlProps = React.HTMLAttributes<HTMLUListElement>;
export declare type HTMLVideoProps = React.VideoHTMLAttributes<HTMLVideoElement>;
export declare type HTMLWbrProps = React.HTMLAttributes<HTMLElement>;
