export const block: string;
export const isSmall: string;
export const isMedium: string;
export const isLarge: string;
export const heading: string;
export const highlight: string;
export const loader: string;
export const spinAround: string;
export const number: string;
